config/routes.rb
Fountain::Application.routes.draw do

match "/auth/failure" => redirect("/")
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
    resources :photos
  end
  resources :comments
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_many :comments
  belongs_to :user
  attr_accessible :description, :filter, :name, :url
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET users/1/photos
  # GET users/1/photos.json
  def index
    @user = User.find(params[:user_id])
    @photos = @user.photos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET users/1/photos/1
  # GET users/1/photos/1.json
  def show
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:id])
    @comment =  @photo.comments.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET users/1/photos/new
  # GET users/1/photos/new.json
  def new
    @user = User.find(params[:user_id])
    @photo = @user.photos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET users/1/photos/1/edit
  def edit
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:id])
  end

  # POST users/1/photos
  # POST users/1/photos.json
  def create
    @user = User.find(params[:user_id])
    @photo = @user.photos.build(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to([@photo.user, @photo], :notice => 'Photo was successfully created.') }
        format.json { render :json => @photo, :status => :created, :location => [@photo.user, @photo] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT users/1/photos/1
  # PUT users/1/photos/1.json
  def update
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to([@photo.user, @photo], :notice => 'Photo was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE users/1/photos/1
  # DELETE users/1/photos/1.json
  def destroy
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to user_photos_url(user) }
      format.json { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for([@photo.user, @photo]) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :filter %><br />
    <%= f.text_field :filter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', [@photo.user, @photo] %> |
<%= link_to 'Back', user_photos_path(@photo.user) %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Url</th>
    <th>Filter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.name %></td>
    <td><%= photo.description %></td>
    <td><img src="<%= photo.url %>" width="200" ></a></td>
    <td><%= photo.filter %></td>
    <td><%= link_to 'Show', [photo.user, photo] %></td>
    <td><%= link_to 'Edit', edit_user_photo_path(photo.user, photo) %></td>
    <td><%= link_to 'Destroy', [photo.user, photo], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_user_photo_path(params[:user_id]) %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', user_photos_path(@photo.user) %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @photo.name %>
</p>

<p>
  <b>Description:</b>
  <%= @photo.description %>
</p>

<p>
	<img src="<%= @photo.url %>" width="200" ></a>
  
</p>

<p>
  <b>Filter:</b>
  <%= @photo.filter %>
</p>
<h3>Comments</h3>
<% @photo.comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %><p>
  </div>
<% end %>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_user_photo_path(@photo.user, @photo) %> |
<%= link_to 'Back', user_photos_path(@photo.user) %>